# Generated by Django 4.0.4 on 2022-06-04 14:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("user_profile", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="customuser",
            name="avatar",
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
